# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shlink-client
  namespace: shlinklaksjdfkajsdf
  labels:
    app: shlink-client
spec:
  selector:
    matchLabels:
      app: shlink-client
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: shlink-client
    spec:
      containers:
      - name: shlink-client
        image: shlinkio/shlink-web-client
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8080
        env:
        - name: SHLINK_SERVER_NAME
          valueFrom:
            configMapKeyRef:
              name: shlink-client-cm
              key: server_name

        - name: SHLINK_SERVER_URL
          valueFrom:
            configMapKeyRef:
              name: shlink-client-cm
              key: server_url

        - name: SHLINK_SERVER_API_KEY
          valueFrom:
           secretKeyRef:
              name: shlink-client-api-key
              key: api_key

        ports:
        - containerPort: 8080
          name: shlink-client
      restartPolicy: Always
---
# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: shlink-client-svc
  namespace: shlink
spec:
  selector:
    app: shlink-client
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
---
# https://kubernetes.io/docs/concepts/services-networking/ingress/
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shlink-client-ingress
  namespace: shlink
spec:
  rules:
  - host: shlink-client.pupy.cloud
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: shlink-client-svc
            port:
              number: 80
  tls:
    - hosts:
        - '*.pupy.cloud'
      secretName: le-wildcard-pupy-cloud-tls
---
# https://kubernetes.io/docs/concepts/configuration/configmap/
apiVersion: v1
kind: ConfigMap
metadata:
  name: shlink-client-cm
  namespace: shlink
data:
  server_name: internal
  server_url: http://shlink-kube.pupy.cloud
---
