# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
    name: gitlab-token
    namespace: flux-system
type: Opaque
# note to self: this PAT needs "Developer" role or higher
stringData:
    token: ENC[AES256_GCM,data:qwDvlmuqJLI/0ggFGNjSxlti6EDCdIO0qUs=,iv:NV5k9MubjS4B9iyspXBkgfnE/Csz4oOhH9w8U3VQEJ0=,tag:2QLoReR1O1bF9GQEqUSIzg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yaeq49xp06dguajrxg582knly6ewkarszs6mmq22tq8c0de339aqc6rqzd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoQnNIMXc3Ym9LR1JBaWxn
            eDlRazhVNFJJb2hTK3V2V2hFblM3OFFQcDBBCnUzMms4SXNTU0h4Sk50WnIrMEdi
            LzcyUmMzYXFwUHpNM2I4bGJlT3M1SUEKLS0tIHpYMlhCRkU1bTd0S1NGVWQ4RWIy
            clptUUJCVUVzVUFXZDFHcElnVXdUM1UKeWsWjhOrJZVPgHv4bRtSlFO60OI2sJqM
            v1L7fKzKYsNxDBPplGCar35TFzETlQvud21aKNN7DBPuRGAL0Tc86A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-23T00:59:31Z"
    mac: ENC[AES256_GCM,data:SdTXLN8b7s7TI2x1Ky5m7LsZDTfOAlUlqT6Zq3FbtwDpAmP8UHVtUpMlDwYehCkCUwswOvNxmV76TMCiVbpqiYHBaBSsfvESziFnDAv4VGFI+/TmAirxcJVnzfOfY3cV6ytVnJxdvsdOGnGSbhYEI40fMG0z0mcWvAcfP7iYUPM=,iv:Vqd1ibqdB+tXG4lAroGJ6eu36wjXZThLeQ7KMQRPAEU=,tag:yDhEWRX+B15JrT/nf9Vwsw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
