# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
    name: gitlab-token
    namespace: flux-system
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:qwDvlmuqJLI/0ggFGNjSxlti6EDCdIO0qUs=,iv:NV5k9MubjS4B9iyspXBkgfnE/Csz4oOhH9w8U3VQEJ0=,tag:2QLoReR1O1bF9GQEqUSIzg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yaeq49xp06dguajrxg582knly6ewkarszs6mmq22tq8c0de339aqc6rqzd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoQnNIMXc3Ym9LR1JBaWxn
            eDlRazhVNFJJb2hTK3V2V2hFblM3OFFQcDBBCnUzMms4SXNTU0h4Sk50WnIrMEdi
            LzcyUmMzYXFwUHpNM2I4bGJlT3M1SUEKLS0tIHpYMlhCRkU1bTd0S1NGVWQ4RWIy
            clptUUJCVUVzVUFXZDFHcElnVXdUM1UKeWsWjhOrJZVPgHv4bRtSlFO60OI2sJqM
            v1L7fKzKYsNxDBPplGCar35TFzETlQvud21aKNN7DBPuRGAL0Tc86A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-23T00:57:18Z"
    mac: ENC[AES256_GCM,data:g+DAkGsqdx7b+Y1Vd4HywOvkCn6ihAxNqdceZl+Njk25zm7+XflNQeIT9mAW8mWIUx65gvJRl72SYxSlPuDuPnE4XSWPrnyBPAZytcba856f9RHeQRJ3XMjADlfEcVLjTLu+NkFk+hJXYf27lLRUE00ky+J+Wv/oHcrlC9UAnKM=,iv:iNdcgd5p1KASL7sXlrBASvrnpDsPtOW5LykBHuoq7Cs=,tag:hF02PcsFrZhTN9REk9yPhg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
