# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
    name: gitlab-token
    namespace: flux-system
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:bcgvjSfMJ8Pcmblh39P/1m6OSXWhMmTtzyI=,iv:mAOKEWXYb0aZXVMnr58PQ40QZbAUL9ebLgxtlNlq1rY=,tag:12rMEX0G+S+rMBGf7sT/Jw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yaeq49xp06dguajrxg582knly6ewkarszs6mmq22tq8c0de339aqc6rqzd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoQnNIMXc3Ym9LR1JBaWxn
            eDlRazhVNFJJb2hTK3V2V2hFblM3OFFQcDBBCnUzMms4SXNTU0h4Sk50WnIrMEdi
            LzcyUmMzYXFwUHpNM2I4bGJlT3M1SUEKLS0tIHpYMlhCRkU1bTd0S1NGVWQ4RWIy
            clptUUJCVUVzVUFXZDFHcElnVXdUM1UKeWsWjhOrJZVPgHv4bRtSlFO60OI2sJqM
            v1L7fKzKYsNxDBPplGCar35TFzETlQvud21aKNN7DBPuRGAL0Tc86A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-23T00:50:02Z"
    mac: ENC[AES256_GCM,data:3OmRmAF5rLVQDWH54lx2TDXFTlIIZmdNJpGt06HWnahJ8sqVHS/w5xk5zAFxpAkNMUIAjzAv5+bV1osqdvTSnAVnPNzcI+uNGcZL3Ji+U5iKarA0Emuobfk2TwfjJEqV1MxEGhlOQoNyeaEdobPmgSdtqKBJNEmjtKrywSpIhMA=,iv:l0hwPVRiwuGd49WS3xJXELe56z3Vi5lTlTpBvxvpHZM=,tag:cYmnB7TbNQpSne/jLNbV5g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
