# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
    name: gitlab-token
    namespace: flux-system
type: Opaque
# note to self: this PAT needs "Developer" role or higher
stringData:
    #ENC[AES256_GCM,data:+9A88bT7GvzHnBGfLHZOhv9jd6T6E3gfA9WVEXGOi/+Glg==,iv:F3w+i8LP8PgF9BuNGxnddVefkLS4sckM5MiA5Hy4FNc=,tag:YGh6iOBjsomoI24BTcCe4g==,type:comment]
    token: ENC[AES256_GCM,data:Jw7UxIzaVlzsLsRvXYeUZZ21u1YJbZB6KrY=,iv:JfIETgor9PDagfFxvsXIS37b8Sc/TwbKAsHF6jdZ0f8=,tag:Uvkm5Glfn94qpWcM5noGrQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yaeq49xp06dguajrxg582knly6ewkarszs6mmq22tq8c0de339aqc6rqzd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoQnNIMXc3Ym9LR1JBaWxn
            eDlRazhVNFJJb2hTK3V2V2hFblM3OFFQcDBBCnUzMms4SXNTU0h4Sk50WnIrMEdi
            LzcyUmMzYXFwUHpNM2I4bGJlT3M1SUEKLS0tIHpYMlhCRkU1bTd0S1NGVWQ4RWIy
            clptUUJCVUVzVUFXZDFHcElnVXdUM1UKeWsWjhOrJZVPgHv4bRtSlFO60OI2sJqM
            v1L7fKzKYsNxDBPplGCar35TFzETlQvud21aKNN7DBPuRGAL0Tc86A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-28T21:28:23Z"
    mac: ENC[AES256_GCM,data:kRjsCa0dwwtQCNSB9C+sZrZOJlzfixL5U111UdyM3QROGBG4WvcCHZinTm9yYWAa8qMdTMKD1zYo/+DLpk/5+OhehI8pG0GAUyMClTb9ZM7Qd8zZvqQJRNwqJj57dpemCwKUvPP5fS378SZa1mOCbCdYiGyRfBTdzOElfEzpHdw=,iv:veM9HICN2G+c9tp7ZGEAusc+RJaRNeHgstmQCyxq+B0=,tag:1l1xXoZeyiy6xS3jaU8iTA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
