apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
- discord-webhook.yaml
- discord-provider.yaml
- discord-alerts.yaml
- gitlab-provider.yaml
