# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.30.0/service-v1.json

apiVersion: v1
kind: Service

metadata:
  name: echo-server
  namespace: echo-server

spec:
  type: LoadBalancer
  selector:
    app: echo-server

  ports:
    - port: 80
      targetPort: 80
      name: http
      protocol: TCP
