apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
  namespace: external-dns
spec:
  selector:
    matchLabels:
      app: external-dns
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      serviceAccountName: external-dns
      containers:
        - name: external-dns
          image: registry.k8s.io/external-dns/external-dns:v0.14.2
          args:
            - --registry=txt
            - --txt-prefix=external-dns-
            - --txt-owner-id=k8s
            - --provider=rfc2136
            - --rfc2136-host=192.168.8.206
            - --rfc2136-port=5301
            - --rfc2136-zone=k8s.pupy.cloud
            - --rfc2136-zone=pupy.cloud
            - --rfc2136-tsig-axfr
            - --source=ingress
            - --domain-filter=k8s.pupy.cloud
            - --domain-filter=pupy.cloud
            - --ignore-ingress-tls-spec
          envFrom:
            - secretRef:
                name: tsig-creds
