resources:
  - ../arr-base

labels:
  - pairs:
      app: filebrowser
    includeSelectors: true
    includeTemplates: true

namePrefix: filebrowser-

patches:
  - target:
      kind: Ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: filebrowser-kube.pupy.cloud

  - target:
      kind: Deployment
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/ports/0/containerPort
        value: 80

images:
  - name: scratch
    newName: filebrowser/filebrowser
    newTag: s6
