# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
    name: unpackerr-credentials
    namespace: media
stringData:
    UN_SONARR_0_API_KEY: ENC[AES256_GCM,data:KyBO5BFR55j+JI/ipZ51xfIKle4z5lO/janzl6SLsrQ=,iv:2NrnQksJ6/XRTO97lDTi21/PNeSmpj3PsdPigxS9wd4=,tag:X0vz6v9oZzBD35p2DO95Eg==,type:str]
    UN_RADARR_0_API_KEY: ENC[AES256_GCM,data:o1+GcJRC2joi16PPUXYORjK5NeiKw/+HXqw1EYkAZ2c=,iv:552YI891dqwJQkTLDaKNbNhw3fvprNoPMCt8EOF+s04=,tag:455x6dRYDkZQ+xAzTElhtA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yaeq49xp06dguajrxg582knly6ewkarszs6mmq22tq8c0de339aqc6rqzd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBveUFKaXc2SGFjS0tSR2JE
            Rndzc21MSHBET2xsUDdYYUFzdmk5SHpMalhjCnVTWEhiZ01MVi84QytRSE5wRGpp
            K3VQNTZHWGM5UVdPdk9PY1Y0YzFNYkEKLS0tIGlGQ3dYbUVxalIwalc0QnIwd2xT
            Q1NHSWRSRFBUZkZrREN2NXFuWDdCM3MKglvKTbbNrzFVgcKnWObUIgrEXqzPNNTQ
            9ynz1UYNPscXDIIzyZ330bPG5Fb1acXTjc9S4euaIurK73PIo2SHyw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-21T03:06:15Z"
    mac: ENC[AES256_GCM,data:5aI6xH9cwd5s8oqrOk8dL1+ixizqQed5PtoBD+USb85KTDxSqWxijyzyeCfs7JDKKXdYKBcN/ffnOGuEBGWrsa6WzKv1aZe5Z44rDNAXzpa/a8P4vlnbDNCFso+tFwNm0H0uNRxVTEnCXGjOMnGj+wn5GUSDm6nUL4/e7pM2r0k=,iv:XhFMLyGgPolF1WPi1myIR5m149p7L7EdEhGwTnqlNF0=,tag:nRrDFJA2aRpkJSLuuqDojg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
