# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
    name: qbittrrent-login
    namespace: media
type: Opaque
stringData:
    QBT_USERNAME: ENC[AES256_GCM,data:cIjMi+w=,iv:7F6XoyRs9MXoKCHVS+5cvGbli9Qvr0D0sgmOmez0Hh0=,tag:YXAxxfW8Y8f+uurCOeILVw==,type:str]
    QBT_PASSWORD: ENC[AES256_GCM,data:SQI7ra8G,iv:MHHvmsvla2OSqKqwHmDdOSDGTeYKKG8J/kJAf1YxRiM=,tag:Fp7Wa/r/DVMklORz1LcaCg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yaeq49xp06dguajrxg582knly6ewkarszs6mmq22tq8c0de339aqc6rqzd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6eWVUaVRVd293bEM4TXlF
            MzVwNFlSS2xOSm1tMmZKYXl3U1F3bWtJUjM0CnJqMUZJRGtWaHNzdG4wSHRuTjk2
            RVd6NUY0VDVERVBCZlZidm9KM3hCVzAKLS0tIDRRbDBPY3F6d0YreEt1RjArL253
            ZkxsTExPWVgwRktiYk93REdFSExUZzgKiKndMGZ6wPqs/OJ5KlHHIKDl6EYM0fcO
            4db5CyYO+BJpsS4lTuG/FTSK61uaTABtGBeVSii2eWyxGY5f5oBfdg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-20T00:45:26Z"
    mac: ENC[AES256_GCM,data:8HI7evps1MMonvaTMyvP28mVydx0FNLc6rTpfnzlmDZeURR49YEKEs0rC0AkmsVSo3JtV9WiLFSnnZNwLidtRnD142/wD9B6D90NoS99LVdrs9qZurRdxvQTyNkK/hi5yA/hLBpvEmVDy1klcf/gBmUBSBR3KfVdnThFeWXnYYw=,iv:NJ4IM5sSojXJkhx+pnHaJ5nA430IYiVC7H3P0X0T17s=,tag:2RCvwaIZSvif2jytTs4ZLA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
