resources:
  - ../arr-base

labels:
  - pairs:
      app: radarr
    includeSelectors: true
    includeTemplates: true

namePrefix: radarr-

patches:
  - target:
      kind: Ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: radarr-kube.pupy.cloud

  - target:
      kind: Deployment
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/ports/0/containerPort
        value: 7878

images:
  - name: scratch
    newName: lscr.io/linuxserver/radarr
