apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config
spec:
  storageClassName: longhorn
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      # these apps suck and store logs here for some reason
      storage: 200Mi
